### ISSUE TITLE
Improve Account Info Structs and GetAccount(s)()

### ISSUE THREAD

**Issue by jazzboME** [go-schwab/trader#72]
### what would you like to see (describe affect rather than mechanism, if possible)?

Initially I'm working on an app to monitor my accounts (rather than initiate trades) and with the current state of trader I'm getting very little account information. What I would like to do is:

a) Update the structs to match the results from the API.
b) change the definitions of:
`func (agent *Agent) GetAccounts() ([]Account, error)
`to
`func (agent *Agent) GetAccounts(fields ...string) ([]Account, error)
`
and
`func (agent *Agent) GetAccount(id string) (Account, error)
`to
`func (agent *Agent) GetAccount(id string, fields ...string) (Account, error)
`

By using variadics here, it should be non-breaking for existing code and easily allow the ability to use the fields parameter with the calls. (Currently the API only has "positions" defined for fields.)

If you're okay with this approach, I can initiate a pull request from my fork to implement this.

**Comment by samjtro** [comment]
@jazzboME would love to see what you've done here! i've been mostly prioritizing revamping market data so i haven't been able to get much done with respect to accounts & trading.

i'm in the middle of overhauling the contribution system, can you make a preliminary pr to the dev branch so i can take a look?
